// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkonlwtmgegrqikmvcfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrb25sd3RtZ2VncnFpa212Y2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDE2MzMsImV4cCI6MjA3NDExNzYzM30.EjPsMqwCz7gXFXtrrg4uOIOkXkmouTbEXdahMOj7VQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});